heat_template_version: 2014-10-16

description: >
  vEPC

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for server. Please use an Ubuntu based image.
    default: VCM_IMG
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used on the compute instance.
    default: m1.medium
  security_group_def:
    type: string
    default: default
  public_network:
    type: string
    label: Public network name or ID
    description: Public network to attach server to.
    default: net04_ext
  availability_zone_1:
    type: string
    label: availability_zone for VMs
    default: nova
  availability_zone_2:
    type: string
    label: availability_zone for VMs
    default: nova
  private_network:
    type: string
    label: Private network name or ID
    description: Network to attach server to.
    default: net04
  index:
    type: number
    description: Index of node in the cluster
    default: 0
  index_2:
    type: number
    description: Index of node in the cluster
    default: 10


  sgi_net_name:
    type: string
    description: Private network address (CIDR notation)
    default: SGi-0
  sgi_net_cidr:
    type: string
    description: Private network address (CIDR notation)
    default: 172.16.20.0/24
  sgi_net_pool_start:
    type: string
    description: Start of private network IP address pool
    default: 172.16.20.10
  sgi_net_pool_end:
    type: string
    description: End of private network IP address pool
    default: 172.16.20.30


  s1_net_name:
    type: string
    description: Private network address (CIDR notation)
    default: S1-0
  s1_net_cidr:
    type: string
    description: Private network address (CIDR notation)
    default: 172.16.10.0/24
  s1_net_pool_start:
    type: string
    description: Start of private network IP address pool
    default: 172.16.10.10
  s1_net_pool_end:
    type: string
    description: End of private network IP address pool
    default: 172.16.10.30

  security_group_name:
    type: string
    description: End of private network IP address pool
    default: vEPC_sec_grp
resources:
  vEPC_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: {get_param: security_group_name}
      description: Security group for all vEPC components
      rules:
        # All egress traffic
        - direction: egress
          ethertype: IPv4
        - direction: egress
          ethertype: IPv6
        # ICMP
        - protocol: icmp
        # SSH
        - protocol: tcp
          port_range_min: 22
          port_range_max: 22
        # SNMP
        - protocol: udp
          port_range_min: 161
          port_range_max: 161

  sgi_network:
    type: OS::Neutron::Net
    properties:
      name: { get_param: sgi_net_name }

  sgi_network_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: { get_param: sgi_net_name }
      network_id: { get_resource: sgi_network }
      cidr: { get_param: sgi_net_cidr }
      allocation_pools:
        - start: { get_param: sgi_net_pool_start }
          end: { get_param: sgi_net_pool_end }

  s1_network:
    type: OS::Neutron::Net
    properties:
      name: { get_param: s1_net_name }

  s1_network_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: { get_param: s1_net_name }
      network_id: { get_resource: s1_network }
      cidr: { get_param: s1_net_cidr }
      allocation_pools:
        - start: { get_param: s1_net_pool_start }
          end: { get_param: s1_net_pool_end }


  VCM_CDF:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_CDF.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_1}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_param: private_network}
          index: {get_param: index}

  VCM_CPE:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_CPE.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_1}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_param: private_network}
          index: {get_param: index}

  VCM_SDB:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_SDB.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_1}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_param: private_network}
          index: {get_param: index}

  VCM_UDB:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_UDB.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_1}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_param: private_network}
          index: {get_param: index}

  VCM_VEM:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_VEM.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_1}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_param: private_network}
          index: {get_param: index}


  sgi_port:
    type: OS::Neutron::Port
    properties:
      name: sgi
      network_id: { get_resource: sgi_network}
      security_groups:
        - { get_resource: vEPC_security_group }

  s1_port_dpe:
    type: OS::Neutron::Port
    properties:
      name: s1_u
      network_id: { get_resource: s1_network}
      security_groups:
        - { get_resource: vEPC_security_group }

  s1_port_rif:
    type: OS::Neutron::Port
    properties:
      name: s1_mme
      network_id: { get_resource: s1_network}
      security_groups:
        - { get_resource: vEPC_security_group }


  VCM_RIF:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_RIF.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_1}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_param: private_network}
          index: {get_param: index}
          port_s1_id: {get_resource: s1_port_rif }

  VCM_DPE:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_DPE.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_1}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_param: private_network}
          index: {get_param: index}
          port_sgi_id: {get_resource: sgi_port }
          port_s1_id: {get_resource: s1_port_dpe }






  VCM_CDF_2:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_CDF.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_2}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_param: private_network}
          index: {get_param: index_2}

  VCM_CPE_2:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_CPE.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_2}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_param: private_network}
          index: {get_param: index_2}

  VCM_SDB_2:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_SDB.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_2}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_param: private_network}
          index: {get_param: index_2}

  VCM_UDB_2:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_UDB.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_2}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_param: private_network}
          index: {get_param: index_2}

  VCM_VEM_2:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_VEM.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_2}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_param: private_network}
          index: {get_param: index_2}


  sgi_port_2:
    type: OS::Neutron::Port
    properties:
      name: sgi_2
      network_id: { get_resource: sgi_network}
      security_groups:
        - { get_resource: vEPC_security_group }

  s1_port_dpe_2:
    type: OS::Neutron::Port
    properties:
      name: s1_u_2
      network_id: { get_resource: s1_network}
      security_groups:
        - { get_resource: vEPC_security_group }

  s1_port_rif_2:
    type: OS::Neutron::Port
    properties:
      name: s1_mme_2
      network_id: { get_resource: s1_network}
      security_groups:
        - { get_resource: vEPC_security_group }


  VCM_RIF_2:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_RIF.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_2}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_param: private_network}
          index: {get_param: index_2}
          port_s1_id: {get_resource: s1_port_rif_2 }

  VCM_DPE_2:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_DPE.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_2}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_param: private_network}
          index: {get_param: index_2}
          port_sgi_id: {get_resource: sgi_port_2 }
          port_s1_id: {get_resource: s1_port_dpe_2 }


outputs:
  CDF_ip:
    description: IP address VCM-CDF-1
    value: { get_attr: [ VCM_CDF, floating_ip ] }

  CPE_ip:
    description: IP address of VCM-CPE-1
    value: { get_attr: [ VCM_CPE, floating_ip ] }

  SDB_ip:
    description: IP address of VCM-SDB-1
    value: { get_attr: [ VCM_SDB, floating_ip ] }

  UDB_ip:
    description: IP address of VCM-UDB-1
    value: { get_attr: [ VCM_UDB, floating_ip ] }

  VEM_ip:
    description: IP address of VCM-VEM-1
    value: { get_attr: [ VCM_VEM, floating_ip ] }

  RIF_ip:
    description: IP address of VCM-RIF-1
    value: { get_attr: [ VCM_RIF, floating_ip ] }

  DPE_ip:
    description: IP address of VCM-DPE-1
    value: { get_attr: [ VCM_DPE, floating_ip ] }


  CDF_2_ip:
    description: IP address VCM-CDF-2
    value: { get_attr: [ VCM_CDF_2, floating_ip ] }

  CPE_2_ip:
    description: IP address of VCM-CPE-2
    value: { get_attr: [ VCM_CPE_2, floating_ip ] }

  SDB_2_ip:
    description: IP address of VCM-SDB-2
    value: { get_attr: [ VCM_SDB_2, floating_ip ] }

  UDB_2_ip:
    description: IP address of VCM-UDB-2
    value: { get_attr: [ VCM_UDB_2, floating_ip ] }

  VEM_2_ip:
    description: IP address of VCM-VEM-2
    value: { get_attr: [ VCM_VEM_2, floating_ip ] }

  RIF_2_ip:
    description: IP address of VCM-RIF-2
    value: { get_attr: [ VCM_RIF_2, floating_ip ] }

  DPE_2_ip:
    description: IP address of VCM-DPE-2
    value: { get_attr: [ VCM_DPE_2, floating_ip ] }

  VEM_private_ip:
    description: private IP address of VCM-VEM
    value: { get_attr: [ VCM_DPE, private_ip ] }
