heat_template_version: 2014-10-16

description: >
  vEPC

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for server. Please use an Ubuntu based image.
    default: VCM_IMG
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used on the compute instance.
    default: m1.medium
  public_network:
    type: string
    label: Public network name or ID
    description: Public network to be attached to server
    default: net04_ext
  availability_zone_1:
    type: string
    label: availability_zone for VCM-1 VMs
    default: compute1
  availability_zone_2:
    type: string
    label: availability_zone for VCM-2 VMs
    default: compute2
  index:
    type: number
    description: Index of nodes in VCM-1
    default: 1
  index_2:
    type: number
    description: Index of node in VCM-2
    default: 2
  security_group_name:
    type: string
    description: Name of Security Group 
    default: vEPC_sec_grp
  router_name:
    type: string
    description: Name of router
    default: extrouter

  S1_C_net_name:
    type: string
    description: Name of Private network S1C
    default: S1C
  S1_C_net_cidr:
    type: string
    description: Private network address (CIDR notation)
    default: 172.100.10.0/27
  S1_C_net_pool_start:
    type: string
    description: Start of private network IP address pool
    default: 172.100.10.2
  S1_C_net_pool_end:
    type: string
    description: End of private network IP address pool
    default: 172.100.10.30

  S1_U_net_name:
    type: string
    description: Name of Private network S1U
    default: S1U
  S1_U_net_cidr:
    type: string
    description: Private network address (CIDR notation)
    default: 172.100.11.0/27
  S1_U_net_pool_start:
    type: string
    description: Start of private network IP address pool
    default: 172.100.11.2
  S1_U_net_pool_end:
    type: string
    description: End of private network IP address pool
    default: 172.100.11.30

  S6a_net_name:
    type: string
    description: Name of Private network S6a
    default: S6a
  S6a_net_cidr:
    type: string
    description: Private network address (CIDR notation)
    default: 172.100.13.0/27
  S6a_net_pool_start:
    type: string
    description: Start of private network IP address pool
    default: 172.100.13.2
  S6a_net_pool_end:
    type: string
    description: End of private network IP address pool
    default: 172.100.13.30

  RADIUS_net_name:
    type: string
    description: Name of Private network RADIUS
    default: RADIUS
  RADIUS_net_cidr:
    type: string
    description: Private network address (CIDR notation)
    default: 172.100.14.0/27
  RADIUS_net_pool_start:
    type: string
    description: Start of private network IP address pool
    default: 172.100.14.2
  RADIUS_net_pool_end:
    type: string
    description: End of private network IP address pool
    default: 172.100.14.30

  SGs_net_name:
    type: string
    description: Name of Private network SGs
    default: SGs
  SGs_net_cidr:
    type: string
    description: Private network address (CIDR notation)
    default: 172.100.12.0/27
  SGs_net_pool_start:
    type: string
    description: Start of private network IP address pool
    default: 172.100.12.2
  SGs_net_pool_end:
    type: string
    description: End of private network IP address pool
    default: 172.100.12.30

  SGi_net_name:
    type: string
    description: Name of Private network SGi
    default: SGi
  SGi_net_cidr:
    type: string
    description: Private network address (CIDR notation)
    default: 172.100.15.0/27
  SGi_net_pool_start:
    type: string
    description: Start of private network IP address pool
    default: 172.100.15.2
  SGi_net_pool_end:
    type: string
    description: End of private network IP address pool
    default: 172.100.15.30

  net0_net_name:
    type: string
    description: Name of Private internal network
    default: net0
  net0_net_cidr:
    type: string
    description: Private network address (CIDR notation)
    default: 10.0.0.0/24
  net0_net_pool_start:
    type: string
    description: Start of private network IP address pool
    default: 10.0.0.2
  net0_net_pool_end:
    type: string
    description: End of private network IP address pool
    default: 10.0.0.254

resources:
  vEPC_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: {get_param: security_group_name}
      description: Security group for all vEPC components
      rules:
        # All egress traffic
        - direction: egress
          ethertype: IPv4
        - direction: egress
          ethertype: IPv6
        # ICMP
        - protocol: icmp
        # SSH
        - protocol: tcp
          port_range_min: 22
          port_range_max: 22
        # EMS-comm-port
        - protocol: tcp
          port_range_min: 8980
          port_range_max: 8980
        # All tcp comm
        - protocol: tcp
          port_range_min: 1
          port_range_max: 65535
        # SNMP
        - protocol: udp
          port_range_min: 161
          port_range_max: 161

  net0_network:
    type: network.yaml
    properties:
      private_net_name: { get_param: net0_net_name }
      private_net_cidr: { get_param: net0_net_cidr }
      private_net_pool_start: { get_param: net0_net_pool_start }
      private_net_pool_end: { get_param: net0_net_pool_end }
  S1_C_network:
    type: network.yaml
    properties:
      private_net_name: { get_param: S1_C_net_name }
      private_net_cidr: { get_param: S1_C_net_cidr }
      private_net_pool_start: { get_param: S1_C_net_pool_start }
      private_net_pool_end: { get_param: S1_C_net_pool_end }
  S1_U_network:
    type: network.yaml
    properties:
      private_net_name: { get_param: S1_U_net_name }
      private_net_cidr: { get_param: S1_U_net_cidr }
      private_net_pool_start: { get_param: S1_U_net_pool_start }
      private_net_pool_end: { get_param: S1_U_net_pool_end }
  S6a_network:
    type: network.yaml
    properties:
      private_net_name: { get_param: S6a_net_name }
      private_net_cidr: { get_param: S6a_net_cidr }
      private_net_pool_start: { get_param: S6a_net_pool_start }
      private_net_pool_end: { get_param: S6a_net_pool_end }
  RADIUS_network:
    type: network.yaml
    properties:
      private_net_name: { get_param: RADIUS_net_name }
      private_net_cidr: { get_param: RADIUS_net_cidr }
      private_net_pool_start: { get_param: RADIUS_net_pool_start }
      private_net_pool_end: { get_param: RADIUS_net_pool_end }
  SGs_network:
    type: network.yaml
    properties:
      private_net_name: { get_param: SGs_net_name }
      private_net_cidr: { get_param: SGs_net_cidr }
      private_net_pool_start: { get_param: SGs_net_pool_start }
      private_net_pool_end: { get_param: SGs_net_pool_end }
  SGi_network:
    type: network.yaml
    properties:
      private_net_name: { get_param: SGi_net_name }
      private_net_cidr: { get_param: SGi_net_cidr }
      private_net_pool_start: { get_param: SGi_net_pool_start }
      private_net_pool_end: { get_param: SGi_net_pool_end }

  Router:
    type: router.yaml
    properties:
      router_name: { get_param: router_name }
      public_net: { get_param: public_network }
      net0_subnet: { get_attr: [ net0_network, private_net_subnet ] }
      S1C_subnet: { get_attr: [ S1_C_network, private_net_subnet ] }
      S1U_subnet: { get_attr: [ S1_U_network, private_net_subnet ] }
      SGs_subnet: { get_attr: [ SGs_network, private_net_subnet ] }
      S6a_subnet: { get_attr: [ S6a_network, private_net_subnet ] }
      radius_subnet: { get_attr: [ RADIUS_network, private_net_subnet ] }
      SGi_subnet: { get_attr: [ SGi_network, private_net_subnet ] }

  VCM_VEM:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_VEM.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_1}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_attr: [net0_network, private_net]}
          index: {get_param: index}
          extrouter_id: {get_attr: [Router, router_id]}
  VCM_VEM_2:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_VEM.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_2}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_attr: [net0_network, private_net]}
          index: {get_param: index_2}
          extrouter_id: {get_attr: [Router, router_id]}
  VCM_SDB:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_SDB.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_1}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_attr: [net0_network, private_net]}
          index: {get_param: index}
          extrouter_id: {get_attr: [Router, router_id]}
  VCM_SDB_2:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_SDB.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_2}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_attr: [net0_network, private_net]}
          index: {get_param: index_2}
          extrouter_id: {get_attr: [Router, router_id]}
  VCM_RIF:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_RIF.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_1}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_attr: [net0_network, private_net]}
          S1C_network: {get_attr: [S1_C_network, private_net]}
          SGs_network: {get_attr: [SGs_network, private_net]}
          index: {get_param: index}
          extrouter_id: {get_attr: [Router, router_id]}
  VCM_RIF_2:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_RIF.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_2}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_attr: [net0_network, private_net]}
          S1C_network: {get_attr: [S1_C_network, private_net]}
          SGs_network: {get_attr: [SGs_network, private_net]}
          index: {get_param: index_2}
          extrouter_id: {get_attr: [Router, router_id]}
  VCM_CPE:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_CPE.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_1}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_attr: [net0_network, private_net]}
          index: {get_param: index}
          extrouter_id: {get_attr: [Router, router_id]}
  VCM_CPE_2:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_CPE.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_2}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_attr: [net0_network, private_net]}
          index: {get_param: index_2}
          extrouter_id: {get_attr: [Router, router_id]}
  VCM_DPE:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_DPE.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_1}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_attr: [net0_network, private_net]}
          S1U_network: {get_attr: [S1_U_network, private_net]}
          SGi_network: {get_attr: [SGi_network, private_net]}
          index: {get_param: index}
          extrouter_id: {get_attr: [Router, router_id]}
  VCM_DPE_2:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_DPE.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_2}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_attr: [net0_network, private_net]}
          S1U_network: {get_attr: [S1_U_network, private_net]}
          SGi_network: {get_attr: [SGi_network, private_net]}
          index: {get_param: index_2}
          extrouter_id: {get_attr: [Router, router_id]}
  VCM_UDB:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_UDB.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_1}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_attr: [net0_network, private_net]}
          S6a_network: {get_attr: [S6a_network, private_net]}
          index: {get_param: index}
          extrouter_id: {get_attr: [Router, router_id]}
  VCM_UDB_2:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_UDB.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_2}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_attr: [net0_network, private_net]}
          S6a_network: {get_attr: [S6a_network, private_net]}
          index: {get_param: index_2}
          extrouter_id: {get_attr: [Router, router_id]}
  VCM_CDF:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_CDF.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_1}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_attr: [net0_network, private_net]}
          RADIUS_network: {get_attr: [RADIUS_network, private_net]}
          index: {get_param: index}
          extrouter_id: {get_attr: [Router, router_id]}
  VCM_CDF_2:
    type: OS::Heat::ResourceGroup
    properties:
      resource_def:
        type: VCM_CDF.yaml
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          availability_zone : {get_param: availability_zone_2}
          security_group_def: {get_resource: vEPC_security_group }
          public_network: {get_param: public_network}
          private_network: {get_attr: [net0_network, private_net]}
          RADIUS_network: {get_attr: [RADIUS_network, private_net]}
          index: {get_param: index_2}
          extrouter_id: {get_attr: [Router, router_id]}

outputs:
  CDF_ip:
    description: IP address VCM-CDF-1
    value: { get_attr: [ VCM_CDF, floating_ip ] }

  CPE_ip:
    description: IP address of VCM-CPE-1
    value: { get_attr: [ VCM_CPE, floating_ip ] }

  SDB_ip:
    description: IP address of VCM-SDB-1
    value: { get_attr: [ VCM_SDB, floating_ip ] }

  UDB_ip:
    description: IP address of VCM-UDB-1
    value: { get_attr: [ VCM_UDB, floating_ip ] }

  VEM_ip:
    description: IP address of VCM-VEM-1
    value: { get_attr: [ VCM_VEM, floating_ip ] }

  RIF_ip:
    description: IP address of VCM-RIF-1
    value: { get_attr: [ VCM_RIF, floating_ip ] }

  DPE_ip:
    description: IP address of VCM-DPE-1
    value: { get_attr: [ VCM_DPE, floating_ip ] }


  CDF_2_ip:
    description: IP address VCM-CDF-2
    value: { get_attr: [ VCM_CDF_2, floating_ip ] }

  CPE_2_ip:
    description: IP address of VCM-CPE-2
    value: { get_attr: [ VCM_CPE_2, floating_ip ] }

  SDB_2_ip:
    description: IP address of VCM-SDB-2
    value: { get_attr: [ VCM_SDB_2, floating_ip ] }

  UDB_2_ip:
    description: IP address of VCM-UDB-2
    value: { get_attr: [ VCM_UDB_2, floating_ip ] }

  VEM_2_ip:
    description: IP address of VCM-VEM-2
    value: { get_attr: [ VCM_VEM_2, floating_ip ] }

  RIF_2_ip:
    description: IP address of VCM-RIF-2
    value: { get_attr: [ VCM_RIF_2, floating_ip ] }

  DPE_2_ip:
    description: IP address of VCM-DPE-2
    value: { get_attr: [ VCM_DPE_2, floating_ip ] }
