heat_template_version: 2013-05-23

description: >
  DNS HA

parameters:
  public_mgmt_net_id:
    type: string
    description: ID of public management network
    constraints:
      - custom_constraint: neutron.network
        description: Must be a valid network ID
  private_mgmt_net_id:
    type: string
    description: ID of private management network
    constraints:
      - custom_constraint: neutron.network
        description: Must be a valid network ID
  public_sig_net_id:
    type: string
    description: ID of public signaling network
    constraints:
      - custom_constraint: neutron.network
        description: Must be a valid network ID
  private_sig_net_id:
    type: string
    description: ID of private signaling network
    constraints:
      - custom_constraint: neutron.network
        description: Must be a valid network ID
  private_sig_net_cidr:
    type: string
    description: Private signaling network address (CIDR notation)
    default: 192.168.1.0/24
  flavor:
    type: string
    description: Flavor to use
    constraints:
      - custom_constraint: nova.flavor
        description: Must be a valid flavor name
  image:
    type: string
    description: Name of image to use
    constraints:
      - custom_constraint: glance.image
        description: Must be a valid image name
  key_name:
    type: string
    description: Name of keypair to assign
    constraints:
      - custom_constraint: nova.keypair
        description: Must be a valid keypair name
  dns_security_group:
    type: string
    description: ID of security group for DNS nodes
  zone:
    type: string
    description: DNS zone
    default: example.com
  dnssec_key:
    type: string
    description: DNSSEC private key (Base64-encoded)
  dns_virtual_ip_mgmt:
    type: string
    description: Virtual IP address that can be used on different instances
  dns_virtual_ip_sig:
    type: string
    description: Virtual IP address that can be used on different instances
  index:
    type: number
    description: Node count

resources:
  dns_ha:
    type: OS::Heat::ResourceGroup
    properties:
      count: 2
      resource_def:
        type: ClearwaterIMS::DNS
        properties:
          public_mgmt_net_id: { get_param: public_mgmt_net_id }
          private_mgmt_net_id: { get_param: private_mgmt_net_id }
          public_sig_net_id: { get_param: public_sig_net_id }
          private_sig_net_id: { get_param: private_sig_net_id }
          private_sig_net_cidr: { get_param: private_sig_net_cidr }
          flavor: { get_param: flavor }
          image: { get_param: image }
          key_name: { get_param: key_name }
          dns_security_group: {get_param: dns_security_group}
          zone: { get_param: zone }
          dnssec_key: { get_param: dnssec_key }
          dns_virtual_ip_sig: { get_param: dns_virtual_ip_sig }
          dns_virtual_ip_mgmt: { get_param: dns_virtual_ip_mgmt}
          index: { get_param: index}

outputs:
  private_mgmt_ip_list:
    value: {get_attr: [dns_ha, private_mgmt_ip]}
  private_mgmt_ip_1:
    description: DNS 1 management IP
    value: { get_attr: [dns_ha, resource.0.private_mgmt_ip] }
  private_mgmt_ip_2:
    description: DNS 2 management IP
    value: { get_attr: [dns_ha, resource.1.private_mgmt_ip] }
  private_sig_ip_1:
    description: DNS 1 signaling IP
    value: { get_attr: [dns_ha, resource.0.private_sig_ip] }
  private_sig_ip_2:
    description: DNS 2 signaling IP
    value: { get_attr: [dns_ha, resource.1.private_sig_ip] }
  #dns_public_sig:
  #  description: Public signaling VIP
  #  value: {}
  #dns_public_mgmt:
  #  description: Public management VIP