resource_registry:
        "ClearwaterIMS::Network": "./network.yaml"
        "ClearwaterIMS::SecurityGroups": "./security-groups.yaml"
        "ClearwaterIMS::Bono": "./bono.yaml"
        "ClearwaterIMS::BonoCluster": "./bono_cluster.yaml"
        "ClearwaterIMS::Dime": "./dime.yaml"
        "ClearwaterIMS::DimeCluster": "./dime_cluster.yaml"        
        "ClearwaterIMS::Homer": "./homer.yaml"
        "ClearwaterIMS::HomerCluster": "./homer_cluster.yaml"
        "ClearwaterIMS::Sprout": "./sprout.yaml"
        "ClearwaterIMS::SproutCluster": "./sprout_cluster.yaml"
        "ClearwaterIMS::Vellum": "./vellum.yaml"
        "ClearwaterIMS::VellumCluster": "./vellum_cluster.yaml"
        "ClearwaterIMS::DNS": "./dns.yaml"
        "ClearwaterIMS::DNSHA": "./dns_ha.yaml"
        "ClearwaterIMS::Ellis": "./ellis.yaml"

