heat_template_version: 2013-05-23

description: >
  Scalable Homer Cluster

parameters:
  cluster_size:
    type: number
    description: "Size of Homer cluster"
    default: 2
  public_mgmt_net_id:
    type: string
  private_mgmt_net_id:
    type: string
  public_sig_net_id:
    type: string
  private_sig_net_id:
    type: string
  private_sig_net_cidr:
    type: string
  private_sig_net_gateway:
    type: string
  flavor:
    type: string
  image:
    type: string
  key_name:
    type: string
  base_mgmt_security_group:
    type: string
  homer_mgmt_security_group:
    type: string
  homer_sig_security_group:
    type: string
  repo_url:
    type: string
  zone:
    type: string
  dns_mgmt_ip_1:
    type: string
  dns_mgmt_ip_2:
    type: string
  dns_virtual_ip_mgmt:
    type: string
  dns_virtual_ip_sig:
    type: string
  dnssec_key:
    type: string
  etcd_ip:
    type: string
  #index:
  #  type: string
  #affinity_group:
  #  type: string

resources:
  homer_hard_group:
   type: OS::Nova::ServerGroup
   properties:
    name: Homer VMs on separate compute nodes
    policies:
     - anti-affinity

  homer_soft_group:
   type: OS::Nova::ServerGroup
   properties:
    name: Homer VMs on separate compute nodes with soft anti-affinity
    policies:
     - soft-anti-affinity

  homer_scaleup_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: homer_scale}
      cooldown: 60
      scaling_adjustment: 1

  homer_scaledown_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: homer_scale}
      cooldown: 60
      scaling_adjustment: -1

  homer_scale:
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 0
      desired_capacity: 0
      max_size: {get_param: cluster_size}
      resource:
        type: ClearwaterIMS::Homer
        properties:
          public_mgmt_net_id: { get_param: public_mgmt_net_id }
          private_mgmt_net_id: { get_param: private_mgmt_net_id }
          public_sig_net_id: { get_param: public_sig_net_id }
          private_sig_net_id: { get_param: private_sig_net_id }
          private_sig_net_cidr: { get_param: private_sig_net_cidr }
          private_sig_net_gateway: { get_param: private_sig_net_gateway }
          flavor: { get_param: flavor }
          image: { get_param: image }
          key_name: { get_param: key_name }
          base_mgmt_security_group: { get_param: base_mgmt_security_group }
          homer_mgmt_security_group: { get_param: homer_mgmt_security_group }
          homer_sig_security_group: { get_param: homer_sig_security_group }
          repo_url: { get_param: repo_url }
          zone: { get_param: zone }
          dns_mgmt_ip_1: { get_param: dns_mgmt_ip_1 }
          dns_mgmt_ip_2: { get_param: dns_mgmt_ip_2 }
          dns_virtual_ip_mgmt: { get_param: dns_virtual_ip_mgmt }
          dns_virtual_ip_sig: { get_param: dns_virtual_ip_sig }
          dnssec_key: { get_param: dnssec_key }
          etcd_ip: { get_param: etcd_ip }
          affinity_group: { get_resource: homer_soft_group}

  homer_init:
    type: OS::Heat::ResourceGroup
    properties:
      count: 2
      resource_def:
        type: ClearwaterIMS::Homer
        properties:
          public_mgmt_net_id: { get_param: public_mgmt_net_id }
          private_mgmt_net_id: { get_param: private_mgmt_net_id }
          public_sig_net_id: { get_param: public_sig_net_id }
          private_sig_net_id: { get_param: private_sig_net_id }
          private_sig_net_cidr: { get_param: private_sig_net_cidr }
          private_sig_net_gateway: { get_param: private_sig_net_gateway }
          flavor: { get_param: flavor }
          image: { get_param: image }
          key_name: { get_param: key_name }
          base_mgmt_security_group: { get_param: base_mgmt_security_group }
          homer_mgmt_security_group: { get_param: homer_mgmt_security_group }
          homer_sig_security_group: { get_param: homer_sig_security_group }
          repo_url: { get_param: repo_url }
          zone: { get_param: zone }
          dns_mgmt_ip_1: { get_param: dns_mgmt_ip_1 }
          dns_mgmt_ip_2: { get_param: dns_mgmt_ip_2 }
          dns_virtual_ip_mgmt: { get_param: dns_virtual_ip_mgmt }
          dns_virtual_ip_sig: { get_param: dns_virtual_ip_sig }
          dnssec_key: { get_param: dnssec_key }
          etcd_ip: { get_param: etcd_ip }
          affinity_group: { get_resource: homer_hard_group}


outputs:
  scaleup_webhook:
    description: Homer webhook for scale up policy
    value: {get_attr: [homer_scaleup_policy, alarm_url]}
  scaledown_webhook:
    description: Homer webhook for scale down policy
    value: {get_attr: [homer_scaledown_policy, alarm_url]}
  #initial_server_names:
  #  value: {get_attr: [homer_init, name]}
  sample_homer:
    description: Sample homer node name
    value: { get_attr: [ homer_init, resource.0.name ] }