# Copyright (C) Metaswitch Networks 2016
# If license terms are provided to you in a COPYING file in the root directory
# of the source code repository by which you are accessing this code, then
# the license outlined in that COPYING file applies to your use.
# Otherwise no rights are granted except for those provided to you by
# Metaswitch Networks in a separate written agreement.

heat_template_version: 2013-05-23

description: >
  Network for Clearwater to use

parameters:
  private_net_name:
    type: string
    description: Name of private network

resources:
  private_net:
    type: OS::Neutron::Net
    properties:
      name: { get_param: private_net_name }

outputs:
  id:
    description: ID of private network
    value: { get_resource: private_net }
  name:
    description: Name of private network
    value: { get_param: private_net_name }
